//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTSRecorder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTSRecorder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите номер из списка!.
        /// </summary>
        internal static string MainWindow_downloadAllBtn_Click_SelectNumberFromList {
            get {
                return ResourceManager.GetString("MainWindow_downloadAllBtn_Click_SelectNumberFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата/Время.
        /// </summary>
        internal static string MainWindow_numbersGV_CellContentDoubleClick_DateTime {
            get {
                return ResourceManager.GetString("MainWindow_numbersGV_CellContentDoubleClick_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжительность.
        /// </summary>
        internal static string MainWindow_numbersGV_CellContentDoubleClick_Duration {
            get {
                return ResourceManager.GetString("MainWindow_numbersGV_CellContentDoubleClick_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл записи.
        /// </summary>
        internal static string MainWindow_numbersGV_CellContentDoubleClick_File {
            get {
                return ResourceManager.GetString("MainWindow_numbersGV_CellContentDoubleClick_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        internal static string MainWindow_numbersGV_CellContentDoubleClick_Type {
            get {
                return ResourceManager.GetString("MainWindow_numbersGV_CellContentDoubleClick_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер.
        /// </summary>
        internal static string MainWindow_numbersGV_Number {
            get {
                return ResourceManager.GetString("MainWindow_numbersGV_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номера.
        /// </summary>
        internal static string NumDGV_Header1 {
            get {
                return ResourceManager.GetString("NumDGV_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация не удалась.
        /// </summary>
        internal static string Worker_GetNumbers_ErrorCaption {
            get {
                return ResourceManager.GetString("Worker_GetNumbers_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте правильность логина и пароля в настройках.
        /// </summary>
        internal static string Worker_GetNumbers_ErrorMessageBox {
            get {
                return ResourceManager.GetString("Worker_GetNumbers_ErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записи на номере отсутствуют.
        /// </summary>
        internal static string Worker_GetRecs_NullRecords {
            get {
                return ResourceManager.GetString("Worker_GetRecs_NullRecords", resourceCulture);
            }
        }
    }
}
